### PR TITLE
Allow admins to reject resource suggestions

### LINKED ISSUE #13: Allow admins to reject resource suggestions
## User story

**As an** admin
**I want** to reject resource suggestions
**So that** I can keep inappropriate content out of the library

## Acceptance criteria

1. **Scenario**: admin sees a reject button
    - **Given**: I am logged in as an admin
    - **And**: there are some suggested resources
    - **When**: I go to the drafts page
    - **Then**: I see a "reject" button alongside the existing "publish" button

2. **Scenario**: admin rejects a suggestion
    - **Given**: I am logged in as an admin
    - **And**: there are some suggested resources
    - **And**: I am on the drafts page
    - **When**: I click the "reject" button on a resource
    - **Then**: the resource is removed from the drafts list
    - **And**: it does not appear on the home page

### PR DESCRIPTION
**Pull request by farzaneh-haghani**
closes #13 

This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

It will show a reject button to allow admin to reject a resource in the draft. It will delete the resource from db.

- **Purpose** -  

Allow admin to reject a suggested resource.

- **How to check** - 

Log in as astronaut, go to suggest tab and fill the from. Then log out and log in as admin and go to draft and find your suggestion. Previously did not have a reject button but now it have and work.

### Author checklist

- [x] I have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [ ] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [ ] I have added a link to this PR to the ticket
- [x] I have made the PR to `main` from a branch named `<category>/<name>`, e.g. `feature/edit-spaceships` or `bugfix/restore-oxygen`
- [x] I have manually tested that the app still works correctly
- [ ] I have requested reviewers here and in my team chat channel

- [ ] I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [ ] I have added tests, or new tests were not required
- [ ] I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required

### CODE REVIEW

**Review by textbook — CHANGES_REQUESTED** [review]
Generally, this is very impressive: well done! 👏 

As an iteration, I'd like to see:

- 🧪 At least one additional test at a different level (i.e. E2E or API integration, not just in the UI
- 📚 Document the API endpoint (either as-is, or you can update as suggested and document the new version)
- ❓ How would you meet the implied requirement of _soft_ deletion (you don't have to implement it, but I'd be interested to hear how you'd approach it)?

(If you'd like to practice on implementing any of the other feedback then you're welcome to, but don't feel you have to.)

---

## Functionality

If I Suggest a draft (as admin or regular user), then visit the Drafts page as an admin, I see:

Screenshot 2024-05-21 at 21 38 42

- ✅  If I click the "Reject" button, the resource is removed from the Drafts page

- ✅ The resource doesn't appear on the home page either

- ❌ The resource is hard-deleted from the DB, note the story links:

    > - Scenario 2 in #15 implies soft deletion

- ❌ UI/UX of deletion could be improved:
    1. Action buttons feel weirdly far apart, it might make more sense to have the buttons in a shared container in the bottom right hand corner
    2. Action buttons are the same colour, easy to mix up at a glance
    3. It's a good principle of interaction design (especially given point 2 and the hard delete) to _require confirmation_ (even a basic [`window.confirm`](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) would do) before doing things that could lead to data loss

---

## Implementation

- ✅ Generally very good; you've put things in sensible places and everything works as you intended

- ❌ From an API design perspective, a `DELETE` request would generally:
    - Have no request body (the resource ID is already in the path)
    - Have no response body (the resource is now "gone" so there's nothing to return)
    - Have a status of 204 No Content

- ❌ No E2E test of the new functionality

- ❌ No integration test or documentation of the new API endpoint, which has a few cases to cover (401 Unauthorized, 403 Forbidden, 404 Not Found and the successful delete -> 200 OK (as-is)/204 No Content (to-be))

---

### Key

- ✅ Nothing to change, just commenting
- 💡 Possible change, or suggestion to think about in the future
- ❓ Discussion required before approval
- ❌ Change required before approval

**Comment by farzaneh-haghani** [comment]
> Generally, this is very impressive: well done! 👏
> 
> As an iteration, I'd like to see:
> 
> * 🧪 At least one additional test at a different level (i.e. E2E or API integration, not just the frontend React tests)
> * 📚 Document the API endpoint (either as-is, or you can update as suggested and document the new version)
> * ❓ How would you meet the implied requirement of _soft_ deletion (you don't have to implement it, but I'd be interested to hear how you'd approach it)?
> 
> (If you'd like to practice on implementing any of the other feedback then you're welcome to, but don't feel you have to.)
> 
> ## Functionality
> If I Suggest a draft (as admin or regular user), then visit the Drafts page as an admin, I see:
> 
> Screenshot 2024-05-21 at 21 38 42
> 
> * ✅  If I click the "Reject" button, the resource is removed from the Drafts page
> * ✅ The resource doesn't appear on the home page either
> * ❌ The resource is hard-deleted from the DB, note the story links:
>   > * Scenario 2 in [Show users their own resource suggestions #15](https://github.com/CodeYourFuture/tech-products-demo/issues/15) implies soft deletion
> * ❌ UI/UX of deletion could be improved:
>   
>   1. Action buttons feel weirdly far apart, it might make more sense to have the buttons in a shared container in the bottom right hand corner
>   2. Action buttons are the same colour, easy to mix up at a glance
>   3. It's a good principle of interaction design (especially given point 2 and the hard delete) to _require confirmation_ (even a basic [`window.confirm`](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) would do) before doing things that could lead to data loss
> 
> ## Implementation
> * ✅ Generally very good; you've put things in sensible places and everything works as you intended
> * ❌ From an API design perspective, a `DELETE` request would generally:
>   
>   * Have no request body (the resource ID is already in the path)
>   * Have no response body (the resource is now "gone" so there's nothing to return)
>   * Have a status of 204 No Content
> * ❌ No E2E test of the new functionality
> * ❌ No integration test or documentation of the new API endpoint, which has a few cases to cover (401 Unauthorized, 403 Forbidden, 404 Not Found and the successful delete -> 200 OK (as-is)/204 No Content (to-be))
> 
> ### Key
> * ✅ Nothing to change, just commenting
> * 💡 Possible change, or suggestion to think about in the future
> * ❓ Discussion required before approval
> * ❌ Change required before approval

Hi @textbook, Can I change the schema of resources? As I understood form the other issue, when the admin reject a resource, user should still see it in another tab to track all own suggested resources. In resources table, we have a draft column which is true by default, then after publish, it would change to false. So how should I flag it as a rejected? Wasn't better if we had a status column (draft / published / rejected)?
status | status-changed-by | status-changed-date
I am not sure if user can edit the suggested resource in the future and suggest it again. In this case, we need to have status table separate from resource table to keep all tracks.

**Comment by textbook** [comment]
> Can I change the schema of resources?

The migrations are there to allow us to [_evolve_](https://martinfowler.com/articles/evodb.html) the schema as needed.

> So how should I flag it as a rejected? Wasn't better if we had a status column (draft / published / rejected)?

Yes, that would be a way to do it - with a boolean we can only represent two states, "draft" or "not draft" (approved). Moving to something with more than two possible values (maybe an [enum](https://www.postgresql.org/docs/current/datatype-enum.html) or look it up from another table, see e.g. https://stackoverflow.com/q/24680744/3001761 for trade offs) allows representing a wider range of states, including "rejected".

>  I am not sure if user can edit the rejected resource in the future and suggest it again. In this case, we need to have status table separate from resource table to keep all tracks.

Currently there's no editing supported and none of the issues propose it, so I wouldn't spend time planning for that now.

**Comment by farzaneh-haghani** [comment]
@textbook Could you please review my changes again.

**Comment by textbook** [comment]
I haven't reviewed it in as much detail this time, but overall that's a good iteration, thank you!

> - 🧪 At least one additional test at a different level (i.e. E2E or API integration, not just the frontend React tests)

✅ Added E2E test _"lets admin users reject drafts"_

> - 📚 Document the API endpoint (either as-is, or you can update as suggested and document the new version)

✅ Existing docs were updated (DELETE endpoint was removed, so no docs needed)

❌  OpenAPI lets you document enums directly, not just as `string`: https://swagger.io/docs/specification/data-models/enums/


> - ❓ How would you meet the implied requirement of soft deletion (you don't have to implement it, but I'd be interested to hear how you'd approach it)?

✅ Implemented by switching from boolean to enum status, so rejection sets resources to `"rejected"`, leaving them in the DB but not returning them to the `?status=drafted` or (usually implicit) `?status=published` queries (although admins _can_ access them by hitting the resource list endpoint - `curl -H 'Authorization: Bearer secretsquirrel' 'http://localhost:4202/api/resources?status=rejected'`)

❌ As in the docs string is too broad for the status parameter, Joi also lets you represent enums https://joi.dev/api/?v=17.13.0#anyvalidvalues---aliases-equal

**Comment by farzaneh-haghani** [comment]
@textbook Thank you. Why did you close it. I can improve it to be merged?

**Comment by textbook** [comment]
It's just an exercise, a work _simulation_. If we merged all of the applications I'd have to keep coming up with new stories (and keep the PR review task branch up-to-date with the changes)!

**Pull request closed without merging**
