### PR TITLE
Add resource details page

### PR DESCRIPTION
**Pull request by Ikamrava**
This is a:

- [x] ✨ **New feature** - new behaviour has been implemented
- [ ] 🐛 **Bug fix** - existing behaviour has been made to behave
- [ ] ♻️ **Refactor** - the behaviour has not changed, just the implementation
- [ ] ✅ **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] ⚙️ **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

Add resource details page

- **Purpose** -  Allow Users to see the details page of every resource. 

- **How to check** - By clicking on the title of every resource you should be directed to the details page related to that resource . 

### Links

[Link to the Page](https://github.com/CodeYourFuture/tech-products-demo/blob/feature/resource-page/pull_request.md)

### Description

Add filter based on resource topic

- **Purpose** -  Allow users to filter all resources based on the resource topic

- **How to check** In the resource page, there is a drop down list that can filter the contents based on the resources

### Links

[Link to the Page](https://github.com/CodeYourFuture/tech-products-demo/issues/30)

### Author checklist

- [x] I have written a title that reflects the relevant ticket
- [x] I have written a description that says what the PR does and how to validate it
- [x] I have linked to the project board ticket (and any related PRs/issues) in the Links section
- [x] I have added a link to this PR to the ticket
- [x] I have made the PR to `main` from a branch named `<category>/<name>`, e.g. `feature/edit-spaceships` or `bugfix/restore-oxygen`
- [x] I have manually tested that the app still works correctly
- [x] I have requested reviewers here and in my team chat channel

- [ ] I have spoken with my PM or TL about any parts of this task that may have become out-of-scope, or any additional improvements that I now realise may benefit my project
- [x] I have added tests, or new tests were not required
- [x] I have updated any documentation (e.g. diagrams, schemas), or documentation updates were not required

### CODE REVIEW

**Comment by Ikamrava** [comment]
I have added a resource details page based on the screen shot provided

**Review by kfklein15 — CHANGES_REQUESTED** [review]
Hi @Ikamrava , can you please fill in the template of your PR. It is there for a reason.

**Comment by Ikamrava** [comment]
> Hi @Ikamrava , can you please fill in the template of your PR. It is there for a reason.

I have done it to the best of my knowledge :)

**Comment by kfklein15** [comment]
> > Hi @Ikamrava , can you please fill in the template of your PR. It is there for a reason.
> 
> I have done it to the best of my knowledge :)

I am still missing 2 fields on it:
Purpose -
How to check -

Can you fill these in, please?

**Comment by Ikamrava** [comment]
> > > Hi @Ikamrava , can you please fill in the template of your PR. It is there for a reason.
> > 
> > 
> > I have done it to the best of my knowledge :)
> 
> I am still missing 2 fields on it: Purpose - How to check -
> 
> Can you fill these in, please?

Should I add them to the PR comment ?

**Comment by Ikamrava** [comment]
I have added a new feature : Filter resources by topic
Purpose : filter the resource list by topic
How to check: I have added a drop down list where you should be able to see the topics and by selecting the topic the content should be filtered.
[Link to the Page](https://github.com/CodeYourFuture/tech-products-demo/issues/30)

**Review by Ikamrava — COMMENTED** [review]
I could use the ID Params instead of search Params that would be a cleaner way but that way I need to add resources in the Resource details and filter the information based on the ID

**Comment by kfklein15** [comment]
> I have added a new feature : Filter resources by topic Purpose : filter the resource list by topic How to check: I have added a drop down list where you should be able to see the topics and by selecting the topic the content should be filtered. [Link to the Page](https://github.com/CodeYourFuture/tech-products-demo/issues/30)

Thanks. Can you please add this directly to your template?

**Comment by textbook** [comment]
Please edit the PR description to complete the template content, as requested above - which issue are you implementing, how should someone check that it is working correctly? Otherwise review cannot proceed.

Also please note that all feature PRs should be based on and target the `main` branch - `feature/resource-page` is **only** for the ["Review a PR"](https://github.com/CodeYourFuture/tech-products-demo?tab=readme-ov-file#review-a-pr) task. It looks like you're _also_ doing #18, in which case it's especially inappropriate to build on top of `feature/resource-page` - did it not seem odd that the resource details page was _already there_?

**Comment by textbook** [comment]
@farzaneh-haghani this is not the PR you're supposed to be reviewing. You need to create a PR _in [your fork](https://github.com/farzaneh-haghani/tech-products-demo)_ from `feature/resource-page` to `main`, then review it there.

**Comment by farzaneh-haghani** [comment]
>  It looks like you're _also_ doing #18, in which case it's especially inappropriate to build on top of `feature/resource-page` 

I think he mixed two tickets. He did Scenario1 of  #30 and a bit of #18.

**Comment by Ikamrava** [comment]
> Please edit the PR description to complete the template content, as requested above - which issue are you implementing, how should someone check that it is working correctly? Otherwise review cannot proceed.
> 
> Also please note that all feature PRs should be based on and target the `main` branch - `feature/resource-page` is **only** for the ["Review a PR"](https://github.com/CodeYourFuture/tech-products-demo?tab=readme-ov-file#review-a-pr) task. It looks like you're _also_ doing #18, in which case it's especially inappropriate to build on top of `feature/resource-page` - did it not seem odd that the resource details page was _already there_?

Sure, I apologize for the mistakes; somehow I got confused about the tasks. I have updated the profile.

**Comment by textbook** [comment]
I don't know what it is you're trying to do here @Ikamrava. You have **two separate tasks** to do:

 1. Review a PR from `feature/resource-page` to `main`, using `pull_request.md` **as the whole description** (note that it is laid out exactly like the PR template - that is very much on purpose), **within your fork** of the repository.

 2. Create a pull request from a feature branch _in your fork_ to `main` _in this repository_, implementing one of the stories listed in [the backlog](https://github.com/CodeYourFuture/tech-products-demo/issues?q=is%3Aopen+is%3Aissue+-label%3Ablocked+label%3A%22%3Asparkles%3A+feature%22), and filling out the PR template accordingly.

Right now you've created one single PR, containing the implementation of #18 you're supposed to be reviewing, plus your own implementation of #18, plus your own implementation of #30, from a feature branch _to a feature branch_. That makes it incredibly difficult to review.

I'm going to close this out for now - I expect to see two _separate_ PRs, one in your repo and one into this repo.

**Pull request closed without merging**
